# Generated by Django 4.0.10 on 2023-07-03 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Категории')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категории',
                'verbose_name_plural': 'Категории',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Comics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('photo', models.ImageField(upload_to='picture/%y/%m/%d/', verbose_name='Фотография')),
                ('file_pdf', models.FileField(upload_to='file/%y/%m/%d/', verbose_name='Файлы')),
                ('content', models.TextField(blank=True, verbose_name='Описание')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновление')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создание')),
                ('is_published', models.BooleanField(default=True, verbose_name='Существует/Несуществует')),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='webcomics.category')),
            ],
            options={
                'verbose_name': 'Комиксы',
                'verbose_name_plural': 'Комиксы',
                'ordering': ['time_create', 'title'],
            },
        ),
    ]
